Default to requiring SSL when connecting to Teiid
release-engineering/estuary-api pull request #310
Opened 2021-06-06 12:52 UTC by mprahl

2021-06-07 07:43 UTC, lioramilbaum requested changes
Can you please provide (at least) unit test?

2021-06-07 11:05 UTC, apaplaus commented on scrapers/teiid.py
> +        :kwarg str sslmode: the Postgres SSL mode to use when connecting to Teiid. This defaults
Maybe it's worth mentioning what other options are acceptable for this parameter?

2021-06-07 11:46 UTC, mulaievaRH approved these changes

2021-06-07 13:35 UTC, mprahl commented
> Can you please provide (at least) unit test?

Unfortunately, the scrapers don't have unit tests since they were only written to be used temporarily until Estuary-Updater was written shortly after. The scrapers have stayed operational to account for message bus outages and/or Estuary-Updater bugs, but unit tests were never added retroactively.

I could add a unit test for just the bit of code that I changed, but it wouldn't really test much other than the keyword argument was passed to pyscopg2. I would rather handle the unit tests of all the scrapers separately. I will file a tech debt ticket for this.

What do you think?

2021-06-07 17:00 UTC, lioramilbaum commented
> > Can you please provide (at least) unit test?
> 
> Unfortunately, the scrapers don't have unit tests since they were only written to be used temporarily until Estuary-Updater was written shortly after. The scrapers have stayed operational to account for message bus outages and/or Estuary-Updater bugs, but unit tests were never added retroactively.
> 
> I could add a unit test for just the bit of code that I changed, but it wouldn't really test much other than the keyword argument was passed to pyscopg2. I would rather handle the unit tests of all the scrapers separately. I will file a tech debt ticket for this.
> 
> What do you think?

I get that there is a technical dept here.  Understood. On the other hand, nobody likes implementing tests. Such a ticket will stay in the backlog for ever until someone deletes it.

Can you implement a unit test only for the function you have touched? 
The unit tests coverage would increase by no time as soon as we embrace this practice.
WDYT?

2021-08-04 18:50 UTC, mprahl commented
I'm not going to get around to finishing this. Feel free to merge it as is or take over the PR.

2024-06-14 18:08 UTC, closed without merging